DATEADD(DAY,DATEDIFF(DAY,1,GETDATE()),0) --PRIOR DAY--
DATEADD(MONTH, -2, GETDATE())  --ADD or REMOVE MONTHS--

DATEADD(MM, DATEDIFF(MM, 0, GETDATE()), 0) --START OF CURRENT MONTH--
DATEADD(DD, -1, DATEADD(MM, DATEDIFF(MM, 0, GETDATE()) +1, 0))  --END OF CURRENT MONTH--
DATEADD(MM, DATEDIFF(MM, 0, GETDATE()) -1, 0) --START OF LAST MONTH--
DATEADD(MM, DATEDIFF(MM, 0, GETDATE()), -1) --END OF LAST MONTH--
DATEADD(MM, DATEDIFF(MM, 0, GETDATE()) + 1, 0) --START OF NEXT MONTH--
DATEADD(DD, -1, DATEADD(MM, DATEDIFF(MM, 0, GETDATE()) +2, 0)) --END OF NEXT MONTH--


DATEADD(QQ, DATEDIFF(QQ, 0, GETDATE()), 0) --START OF CURRENT QUARTER--
DATEADD (DD, -1, DATEADD(QQ, DATEDIFF(QQ, 0, GETDATE()) +1, 0))  --END OF CURRENT QUARTER--
DATEADD(QQ, DATEDIFF(QQ, 0, GETDATE()) -1, 0) --START OF LAST QUARTER--
DATEADD(QQ, DATEDIFF(QQ, 0, GETDATE()), -1) --END OF LAST QUARTER--
DATEADD(QQ, DATEDIFF(QQ, 0, GETDATE()) + 1, 0) --START OF NEXT QUARTER--
DATEADD(DD, -1, DATEADD(QQ, DATEDIFF(QQ, 0, GETDATE()) +2, 0)) --END OF NEXT QUARTER--


DATEADD(YY, DATEDIFF(YY, 0, GETDATE()), 0) --START OF CURRENT YEAR--
DATEADD(DD, -1, DATEADD(YY, DATEDIFF(YY, 0, GETDATE()) +1, 0))  --END OF CURRENT YEAR--
DATEADD(YY, DATEDIFF(YY, 0, GETDATE()) -1, 0) --START OF LAST YEAR--
DATEADD(YY, DATEDIFF(YY, 0, GETDATE()), -1) --END OF LAST YEAR--
DATEADD(YY, DATEDIFF(YY, 0, GETDATE()) +1, 0) --START OF NEXT YEAR--
DATEADD(DD, -1, DATEADD(YY, DATEDIFF(YY, 0, GETDATE()) +2, 0)) --END OF NEXT YEAR--
